const userTypes = {
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",

  SIGN_OUT: "SIGN_OUT",

  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",

  LOAD_PHONE_BOOK_START: "LOAD_PHONE_BOOK_START",
  LOAD_PHONE_BOOK_FAILURE: "LOAD_PHONE_BOOK_FAILURE",
  LOAD_PHONE_BOOK_SUCCESS: "LOAD_PHONE_BOOK_SUCCESS",

  LOAD_CONTACT_START: "LOAD_CONTACT_START",
  LOAD_CONTACT_FAILURE: "LOAD_CONTACT_FAILURE",
  LOAD_CONTACT_SUCCESS: "LOAD_CONTACT_SUCCESS",

  CREATE_PHONE_BOOK_START: "CREATE_PHONE_BOOK_START",
  CREATE_PHONE_BOOK_FAILURE: "CREATE_PHONE_BOOK_FAILURE",
  CREATE_PHONE_BOOK_SUCCESS: "CREATE_PHONE_BOOK_SUCCESS",

  UPDATE_PHONE_BOOK_START: "UPDATE_PHONE_BOOK_START",
  UPDATE_PHONE_BOOK_FAILURE: "UPDATE_PHONE_BOOK_FAILURE",
  UPDATE_PHONE_BOOK_SUCCESS: "UPDATE_PHONE_BOOK_SUCCESS",

  DELETE_PHONE_BOOK_START: "DELETE_PHONE_BOOK_START",
  DELETE_PHONE_BOOK_FAILURE: "DELETE_PHONE_BOOK_FAILURE",
  DELETE_PHONE_BOOK_SUCCESS: "DELETE_PHONE_BOOK_SUCCESS",

  CREATE_CONTACT_START: "CREATE_CONTACT_START",
  CREATE_CONTACT_FAILURE: "CREATE_CONTACT_FAILURE",
  CREATE_CONTACT_SUCCESS: "CREATE_CONTACT_SUCCESS",

  UPDATE_CONTACT_START: "UPDATE_CONTACT_START",
  UPDATE_CONTACT_FAILURE: "UPDATE_CONTACT_FAILURE",
  UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",

  DELETE_CONTACT_START: "DELETE_CONTACT_START",
  DELETE_CONTACT_FAILURE: "DELETE_CONTACT_FAILURE",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",

  LOAD_AUTO_DIALER_START: "LOAD_AUTO_DIALER_START",
  LOAD_AUTO_DIALER_FAILURE: "LOAD_AUTO_DIALER_FAILURE",
  LOAD_AUTO_DIALER_SUCCESS: "LOAD_AUTO_DIALER_SUCCESS",

  CREATE_AUTO_DIALER_START: "CREATE_AUTO_DIALER_START",
  CREATE_AUTO_DIALER_FAILURE: "CREATE_AUTO_DIALER_FAILURE",
  CREATE_AUTO_DIALER_SUCCESS: "CREATE_AUTO_DIALER_SUCCESS",

  UPDATE_AUTO_DIALER_START: "UPDATE_AUTO_DIALER_START",
  UPDATE_AUTO_DIALER_FAILURE: "UPDATE_AUTO_DIALER_FAILURE",
  UPDATE_AUTO_DIALER_SUCCESS: "UPDATE_AUTO_DIALER_SUCCESS",

  DELETE_AUTO_DIALER_START: "DELETE_AUTO_DIALER_START",
  DELETE_AUTO_DIALER_FAILURE: "DELETE_AUTO_DIALER_FAILURE",
  DELETE_AUTO_DIALER_SUCCESS: "DELETE_AUTO_DIALER_SUCCESS",

  LOAD_CALL_RECORD_START: "LOAD_CALL_RECORD_START",
  LOAD_CALL_RECORD_FAILURE: "LOAD_CALL_RECORD_FAILURE",
  LOAD_CALL_RECORD_SUCCESS: "LOAD_CALL_RECORD_SUCCESS",
};

export default userTypes;
